### ISSUE TITLE
Hi, I have a question

### ISSUE THREAD

**Issue by WIttyJudge** [noib3/nvim-cokeline#19] opened 2021-11-11 20:00 UTC
For now, I use standard tabline (with some rewrites).
When I use Nvim Tree, I tap "v" for vertical split, "b" for horizontal, and so on..
If I want to open new tab, I tap "t", but with your plugin (and other like bufferline) when I use vertical split, it opens new tab. How can I fix it or why is it works like that? 

Thank you in advance!

**Comment by noib3** [comment] 2021-11-12 00:06
Could you provide a more step by step way to replicate this issue you're talking about? I'm not sure I understand what the problem is.

**Comment by noib3** [comment] 2022-01-01 15:37
I'm closing this for now. Feel free to comment if you have any more questions.

**Closed by noib3** 2022-01-01 15:37 UTC
Labels: question
