### ISSUE TITLE
E937: Attempt to delete a buffer that is in use

### ISSUE THREAD

**Issue by jqhr** [noib3/nvim-cokeline#64] opened 2022-05-11 09:22 UTC
Environment:
  nvim: 0.7.0
  os: deepin os based on debian 10
Bug reproduce
 When I execute ":bd" cmd after edit GIT MESSAGE. and then:
![图片](https://user-images.githubusercontent.com/23305067/167814733-2642657b-d0c7-4bdc-b070-46dbed65b3b6.png)

**Comment by EtiamNullam** [comment] 2022-05-12 18:30
Duplicate of #60. For now you can leave `buffers.focus_on_delete` as `false` (a default value) to avoid this error until its solved.

**Closed** 2022-05-13 14:19 UTC
